services:
  bd:
    image: mysql
    environment:
      MYSQL_DATABASE: "prueba"
      MYSQL_USER: "2daw"
      MYSQL_PASSWORD: "2daw"
      MYSQL_ROOT_PASSWORD: "2daw"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306

  php:
    image: vicentett1/php-xdebug:1.0
    depends_on:
      - bd
    volumes:
      - type: bind
        source: ./web
        target: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8085:80

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - bd
    ports:
      - 8086:80
    environment:
      - PMA_HOST=BD


volumes:
  mysql-data:


