services:
  php:
    image: vicentett1/php-xdebug:1.0
    volumes:
      - type: bind
        source: ./web
        target: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8085:80